# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
                ('auto_update', models.BooleanField(default=False)),
                ('auto_update_duration', models.IntegerField(default=99999)),
                ('input_file', models.FileField(null=True, upload_to='datasets')),
                ('db_type', models.CharField(max_length=100, null=True)),
                ('db_details', models.TextField(default='{}')),
                ('preview', models.TextField(default='{}')),
                ('meta_data', models.TextField(default='{}')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on', '-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('type', models.CharField(max_length=300, null=True)),
                ('target_column', models.CharField(blank=True, max_length=300, null=True)),
                ('compare_with', models.CharField(default='', max_length=300)),
                ('compare_type', models.CharField(max_length=300, null=True)),
                ('column_data_raw', models.TextField(default='{}')),
                ('config', models.TextField(default='{}')),
                ('status', models.BooleanField(default=False)),
                ('live_status', models.CharField(choices=[('0', 'Not Started Yet'), ('1', 'Signal Creation Started.'), ('2', 'Trend Created'), ('3', 'ChiSquare Created'), ('4', 'Decision Tree Created'), ('5', 'Density Histogram Created'), ('6', 'Regression Created'), ('7', 'Signal Creation Done')], default='0', max_length=300)),
                ('analysis_done', models.BooleanField(default=False)),
                ('data', models.TextField(default='{}')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Dataset')),
            ],
            options={
                'ordering': ['-created_on', '-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=300)),
                ('object_id', models.CharField(max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('slug', models.SlugField(null=True)),
                ('config', models.TextField(default='{}')),
                ('results', models.TextField(default='{}')),
                ('url', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Job'),
        ),
    ]
