# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('config', models.TextField(default='{}')),
                ('data', models.TextField(default='{}')),
                ('model_data', models.TextField(default='{}')),
                ('column_data_raw', models.TextField(default='{}')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Job')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Trainer')),
            ],
        ),
    ]
