# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dataset_file_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='analysis_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='analysis_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='analysis_done',
            field=models.BooleanField(default=False),
        ),
    ]
