# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170904_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robo',
            name='customer_dataset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer_dataset', to='api.Dataset'),
        ),
        migrations.AlterField(
            model_name='robo',
            name='historical_dataset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='historical_dataset', to='api.Dataset'),
        ),
        migrations.AlterField(
            model_name='robo',
            name='market_dataset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='market_dataset', to='api.Dataset'),
        ),
    ]
