# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170904_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='robo',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Job'),
        ),
    ]
