# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dataset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='robo',
            name='status',
            field=models.CharField(default='Not Registered', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.CharField(default='Not Registered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='status',
            field=models.CharField(default='Not Registered', max_length=100, null=True),
        ),
    ]
