# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170907_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='status',
            field=models.CharField(default='Not Registered', max_length=100, null=True),
        ),
    ]
