# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_trainer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='db_details',
            new_name='datasource_details',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='db_type',
            new_name='datasource_type',
        ),
    ]
