# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20170914_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audioset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
                ('auto_update', models.BooleanField(default=False)),
                ('auto_update_duration', models.IntegerField(default=99999)),
                ('input_file', models.FileField(null=True, upload_to='audioset')),
                ('datasource_type', models.CharField(max_length=100, null=True)),
                ('datasource_details', models.TextField(default='{}')),
                ('preview', models.TextField(default='{}')),
                ('meta_data', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('file_remote', models.CharField(max_length=100, null=True)),
                ('analysis_done', models.BooleanField(default=False)),
                ('status', models.CharField(default='Not Registered', max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='dataset',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='robo',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='audioset',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Job'),
        ),
    ]
