# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170918_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robo',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
