# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170918_1016'),
        ('api', '0011_savedata'),
    ]

    operations = [
    ]
