# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20170918_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='subsetting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='slug',
            field=models.SlugField(max_length=300, null=True),
        ),
    ]
