# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20170926_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveanydata',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
