# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20170927_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveanydata',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
