# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20170927_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='app_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
