# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_stockdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdataset',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
