# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_apps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='CustomApps',
        ),
        migrations.AlterField(
            model_name='insight',
            name='compare_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='compare_with',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
