# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20171201_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='customapps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
