# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_job_command_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
