# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0039_auto_20171222_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='submited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
