# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_job_submited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='submited_by',
            new_name='submitted_by',
        ),
    ]
