# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20171226_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error_report',
            field=models.TextField(default='{}'),
        ),
    ]
