# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_dataset_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='message_log',
            field=models.TextField(default='{}'),
        ),
    ]
