# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_job_message_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedata',
            name='object_slug',
            field=models.SlugField(blank=True, default='', max_length=300),
        ),
    ]
