# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_dummy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummy',
            options={'permissions': (('view_task', 'View task'),)},
        ),
    ]
