# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_merge_20180208_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(db_index=True, default='Not Registered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='insight',
            name='status',
            field=models.CharField(db_index=True, default='Not Registered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.CharField(db_index=True, default='Not Registered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='status',
            field=models.CharField(db_index=True, default='Not Registered', max_length=100, null=True),
        ),
    ]
