# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20180215_0829'),
        ('api', '0047_auto_20180215_0710'),
        ('api', '0046_auto_20180206_1102'),
    ]

    operations = [
    ]
