# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_merge_20180215_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioset',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_task', 'View task'),)},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_task', 'View task'),)},
        ),
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_task', 'View task'),), 'verbose_name': 'Signal', 'verbose_name_plural': 'Signals'},
        ),
        migrations.AlterModelOptions(
            name='robo',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_task', 'View task'),)},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_task', 'View task'),)},
        ),
        migrations.AlterModelOptions(
            name='stockdataset',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_task', 'View task'),)},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_task', 'View task'),)},
        ),
    ]
