# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20180215_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
