# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20180215_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioset',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_signal', 'View signal'), ('create_signal', 'Create signal'), ('rename_signal', 'Rename signal'), ('remove_signal', 'remove signal')), 'verbose_name': 'Signal', 'verbose_name_plural': 'Signals'},
        ),
        migrations.AlterModelOptions(
            name='robo',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_score', 'View score'), ('create_score', 'Create score'), ('rename_score', 'Rename score'), ('remove_score', 'remove score'))},
        ),
        migrations.AlterModelOptions(
            name='stockdataset',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_trainer', 'View trainer'), ('create_trainer', 'Create trainer'), ('rename_trainer', 'Rename trainer'), ('remove_trainer', 'remove trainer'))},
        ),
    ]
