# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180215_1017'),
        ('api', '0053_auto_20180219_0724'),
    ]

    operations = [
    ]
