# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0054_merge_20180228_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('column_data_raw', models.TextField(default='{}')),
                ('config', models.TextField(default='{}')),
                ('app_id', models.IntegerField(default=0, null=True)),
                ('data', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('analysis_done', models.BooleanField(default=False)),
                ('status', models.CharField(db_index=True, default='Not Registered', max_length=100, null=True)),
                ('live_status', models.CharField(choices=[('0', 'Not Started Yet'), ('1', 'Signal Creation Started.'), ('2', 'Trend Created'), ('3', 'ChiSquare Created'), ('4', 'Decision Tree Created'), ('5', 'Density Histogram Created'), ('6', 'Regression Created'), ('7', 'Signal Creation Done')], default='0', max_length=300)),
                ('viewed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'permissions': (('view_regression', 'View regression'), ('create_regression', 'Create regression'), ('rename_regression', 'Rename regression'), ('remove_regression', 'remove regression'), ('downlad_pmml', 'Download PMML')),
            },
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_dataset', 'View dataset'), ('create_dataset', 'Create dataset'), ('rename_dataset', 'Rename dataset'), ('remove_dataset', 'remove dataset'), ('upload_from_file', 'Upload from file'), ('upload_from_mysql', 'Upload from mysql'), ('upload_from_mssql', 'Upload from mssql'), ('upload_from_hdfs', 'Upload from hdfs'), ('upload_from_hana', 'Upload from hana'), ('data_validation', 'Data Validation'), ('subsetting_dataset', 'Subsetting dataset'))},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_score', 'View score'), ('create_score', 'Create score'), ('rename_score', 'Rename score'), ('remove_score', 'remove score'), ('download_score', 'Download Score'))},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_trainer', 'View trainer'), ('create_trainer', 'Create trainer'), ('rename_trainer', 'Rename trainer'), ('remove_trainer', 'remove trainer'), ('downlad_pmml', 'Download PMML'))},
        ),
        migrations.AddField(
            model_name='customapps',
            name='app_type',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='regression',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dataset'),
        ),
        migrations.AddField(
            model_name='regression',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Job'),
        ),
    ]
