# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20180228_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regression',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='regression',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='regression',
            name='job',
        ),
        migrations.DeleteModel(
            name='Regression',
        ),
    ]
