# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-25 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_customapps_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdataset',
            options={'ordering': ['-created_at', '-updated_at'], 'permissions': (('view_stock', 'View stock'), ('create_stock', 'Create stock'), ('rename_stock', 'Rename stock'), ('remove_stock', 'remove stock'))},
        ),
    ]
