# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-25 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0059_customappsusermapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customappsusermapping',
            unique_together=set([('user', 'app')]),
        ),
    ]
